server:
  port: ${SERVER_PORT:8082}

spring:
  security:
    user:
      name: "Tharani"
      password: "Jaganath@25"

  application:
    name: USER-SERVICE

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      #ddl-auto: none
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    defer-datasource-initialization: false

    show-sql: true
    # This will FORCE the app to crash if the folder is empty or not found

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    org:
      flywaydb: DEBUG
      springframework:
        jdbc:
          datasource: DEBUG
        jpa:
          hibernate:
            SQL: DEBUG
        boot:
          autoconfigure:
            flyway: DEBUG
app:
  jwtSecret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  jwtExpirationMs: 86400000
