services:
  shopper-ui:
    build:
      context: ../shopper-ui
    container_name: shopper-ui
    ports:
      - "5173:80"
    depends_on:
      - product-service
      - cart-service

  user-db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${USER_DB_NAME}
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}

    ports:
      - "5435:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_DB_USER} -d ${USER_DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 30

  product-db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${PRODUCT_DB_NAME}
      POSTGRES_USER: ${PRODUCT_DB_USER}
      POSTGRES_PASSWORD: ${PRODUCT_DB_PASSWORD}

    ports:
      - "5433:5432"
    volumes:
      - product_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PRODUCT_DB_USER} -d ${PRODUCT_DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 30

  cart-db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${CART_DB_NAME}
      POSTGRES_USER: ${CART_DB_USER}
      POSTGRES_PASSWORD: ${CART_DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - cart_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${CART_DB_USER} -d ${CART_DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 30

#  user-service:
#    image: ktharankumar/user-service:latest
#    build:
#      context: ../java-maven/users
#    container_name: user-service
#    depends_on:
#      user-db:
#        condition: service_healthy
#    environment:
#      SERVER_PORT: 8082
#      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/${USER_DB_NAME}?stringtype=unspecified
#      SPRING_DATASOURCE_USERNAME: ${USER_DB_USER}
#      SPRING_DATASOURCE_PASSWORD: ${USER_DB_PASSWORD}
#      # for actuator exposure if you use profiles
#      SPRING_PROFILES_ACTIVE: docker
#    ports:
#      - "8082:8082"

  product-service:
    image: ktharankumar/product-service:latest
    build:
      context: ../java-maven/products
    container_name: product-service
    depends_on:
      product-db:
        condition: service_healthy
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://product-db:5432/${PRODUCT_DB_NAME}?stringtype=unspecified
      SPRING_DATASOURCE_USERNAME: ${PRODUCT_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${PRODUCT_DB_PASSWORD}
      # for actuator exposure if you use profiles
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8081"

  cart-service:
    image: ktharankumar/cart-service:latest
    build:
      context: ../java-maven/carts
    container_name: cart-service
    depends_on:
      cart-db:
        condition: service_healthy
      product-service:
        condition: service_started
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://cart-db:5432/${CART_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${CART_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${CART_DB_PASSWORD}

      PRODUCT_SERVICE_BASEURL: http://product-service:8081

      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - product-service
      - cart-service

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

  pgadmin4:
    image: dpage/pgadmin4:latest
    ports:
      - "5454:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "ktharankumar@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "Jaganath@25"
    volumes:
      - pgadmin_data:/var/lib/pg_admin

volumes:
  product_db_data:
  cart_db_data:
  user_db_data:
  grafana_data:
  pgadmin_data: